plugins {
    id "application"
    id "com.gradleup.shadow" version "9.0.0-beta8"
    id "java"
}

repositories.mavenCentral()

dependencies {
    implementation "com.google.code.gson:gson:2.12.1"
    implementation "net.lingala.zip4j:zip4j:2.11.5"
    implementation "com.formdev:flatlaf:3.5.4"
}

java { sourceCompatibility = targetCompatibility = "8" }

application.mainClass = "io.github.znemux.mrunpack.Main"

tasks.named("shadowJar", com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveClassifier = ""
    archiveBaseName = "mrunpack"
    exclude("META-INF/proguard/**", "META-INF/maven/**")
    minimize { exclude dependency("com.formdev:flatlaf:.*") }
}

startScripts.enabled = false
startShadowScripts.enabled = false
distTar.enabled = false
distZip.enabled = false
shadowDistTar.enabled = false
shadowDistZip.enabled = false